### ISSUE TITLE
Websocket Errors

### ISSUE THREAD

**Issue by sonicviz** [dongido001/VueVideoChat#1]
Hi,
I've read the article, created the API keys, have the token server running, but get an error running the main app when clicking on a room to open:

MediaClientRemoteDescFailedError {code: 53402, stack: "TwilioError: Client is unable to apply a remote me….all (index 0)↵    at async Promise.all (index 0)", message: "Client is unable to apply a remote media description", name: "TwilioError"}
code: 53402
message: "Client is unable to apply a remote media description"
name: "TwilioError"
stack: "TwilioError: Client is unable to apply a remote media description↵    at MediaClientRemoteDescFailedError.TwilioError (webpack-internal:///./node_modules/twilio-video/lib/util/twilioerror.js:16:21)↵    at new MediaClientRemoteDescFailedError (webpack-internal:///./node_modules/twilio-video/lib/util/twilio-video-errors.js:694:15)↵    at eval (webpack-internal:///./node_modules/twilio-video/lib/signaling/v2/peerconnection.js:625:11)↵    at async Promise.all (index 0)↵    at async Promise.all (index 0)"
__proto__: TwilioError
constructor: ƒ MediaClientRemoteDescFailedError()
__proto__: Error

This is with loglevel set to debug in video.vue
There's some other errors after but this looks like the one causing them I think.

Any clues as to what's wrong?

**Comment by sonicviz** [comment]
Update: Fixed by changing to 
    "twilio-video": "^2.4.0",

**Comment by dongido001** [comment]
Nice
